copy ..\bson\bsonarrayobj.h .
copy ..\bson\bsondefs.h .
copy ..\bson\bsoncontent.h .
copy ..\bson\bson.h .
copy ..\bson\bsonobj.h .
copy ..\bson\bsonparser.h .
copy ..\bson\bsonutil.h .
copy ..\driverbase\djondbconnection.h .
copy ..\driverbase\djondb_client.h .
copy ..\driverbase\djondbconnectionmanager.h .
copy ..\driverbase\djonv8.h .
copy ..\db\constantexpression.h .
copy ..\db\expressionresult.h .
copy ..\db\dbcontroller.h .
copy ..\db\db.h .
copy ..\db\filterdefs.h .
copy ..\db\filter_expressionLexer.h .
copy ..\db\filter_expressionParser.h .
copy ..\db\filterparser.h .
copy ..\db\indexfactory.h .
copy ..\db\index.h .
copy ..\db\indexmanager.h .
copy ..\db\simpleexpression.h .
copy ..\db\streammanager.h .
copy ..\db\unaryexpression.h .
copy ..\db\baseexpression.h .
copy ..\db\binaryexpression.h .
copy ..\db\bplusindex.h .
copy ..\util\logger.h .
copy ..\util\settings.h .
copy ..\util\stringfunctions.h .
copy ..\util\threads.h .
copy ..\util\util.h .
copy ..\util\version.h .
copy ..\util\defs.h .
copy ..\util\datetime.h .
copy ..\util\dtime.h .
copy ..\util\errorhandle.h .
copy ..\util\djon_error_codes.h .
copy ..\util\fileutil.h .
copy ..\util\circular_queue.h .
copy ..\obj\config.h .
