cp ../bson/bsonarrayobj.h .
cp ../bson/bsondefs.h .
cp ../bson/bsoncontent.h .
cp ../bson/bson.h .
cp ../bson/bsonobj.h .
cp ../bson/bsonparser.h .
cp ../bson/bsonutil.h .
cp ../driverbase/djondbconnection.h .
cp ../driverbase/djondbcursor.h .
cp ../driverbase/djondb_client.h .
cp ../driverbase/djondbconnectionmanager.h .
cp ../driverbase/djonv8.h .
cp ../db/constantexpression.h .
cp ../db/expressionresult.h .
cp ../db/dbcontroller.h .
cp ../db/db.h .
cp ../db/filterdefs.h .
cp ../db/filter_expressionLexer.h .
cp ../db/filter_expressionParser.h .
cp ../db/queryparser.h .
cp ../db/filterparser.h .
cp ../db/indexfactory.h .
cp ../db/index.h .
cp ../db/indexmanager.h .
cp ../db/simpleexpression.h .
cp ../db/streammanager.h .
cp ../db/unaryexpression.h .
cp ../db/baseexpression.h .
cp ../db/binaryexpression.h .
cp ../db/bplusindex.h .
cp ../util/logger.h .
cp ../util/settings.h .
cp ../util/stringfunctions.h .
cp ../util/threads.h .
cp ../util/util.h .
cp ../util/version.h .
cp ../util/defs.h .
cp ../util/datetime.h .
cp ../util/dtime.h .
cp ../util/errorhandle.h .
cp ../util/djon_error_codes.h .
cp ../util/fileutil.h .
cp ../util/circular_queue.h .
cp ../build/config.h .
